name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Copy the lib repo
        run: |
          mkdir tmp_lib
          cp -r ./lib/* ./tmp_lib
      - name: Clone libraries
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.lib_repository }}
          path: lib
      - name: Copy the lib repo
        run: |
          cp -r -u ./tmp_lib/* ./lib
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
