name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodule
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
  
  library:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch1
        env:
          MY_SECRET: ${{ secrets.test }}
        if: env.MY_SECRET != null && github.run_number == 1
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.UPDATE_SUBMODULE }}
          repository: Luftalian/Avi_ESP32_lib
          event-type: repository
          client-payload: '{"repo": "${{ github.repository }}"}'
