name: Update Submodule

on:
  repository_dispatch:
    types: [update]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update Submodule
      run: |
        git submodule update --init --recursive
        git submodule update --remote --merge

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        title: 'Update Submodule'
        body: 'An update was made to the submodule.'
        commit-message: 'chore: update submodule'
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        branch: 'update-submodule'
        branch-suffix: timestamp
        delete-branch: true
        labels: dependencies
        token: ${{ secrets.UPDATE_SUBMODULE }}
