name: Update Submodule

on:
  repository_dispatch:
    types: [on-demand-test]

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update Submodule
      run: |
        git submodule update --init --recursive
        git submodule update --remote --merge

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: 'Update Submodule'
        body: 'An update was made to the submodule.'
        commit-message: 'chore: update submodule'
        branch: 'update-submodule'
        branch-suffix: timestamp
        delete-branch: true
        reviewers: octocat
        labels: dependencies
        token: ${{ secrets.UPDATE_SUBMODULE }}
